# Generated by Django 6.1 on 2026-08-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningcontent',
            name='content_url',
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
