# Generated by Django 6.1 on 2026-08-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_remove_learningcontent_content_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcontent',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='content/'),
        ),
    ]
