# Generated by Django 6.1 on 2026-08-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_learningcontent_content_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcontent',
            name='ai_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningcontent',
            name='notes_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
