# Generated by Django 6.1 on 2026-08-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_learningcontent_ai_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcontent',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
