# Generated by Django 6.1 on 2026-08-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_learningcontent_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcontent',
            name='content_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='content/'),
        ),
    ]
