# Generated by Django 6.1 on 2026-08-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_learningcontent_content_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='video_end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='video_start_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
