# Generated by Django 6.1 on 2026-09-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_question_video_end_time_question_video_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pdf_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
