# Generated by Django 6.1 on 2026-09-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_question_pdf_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcontent',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
